# Generated by Django 5.0.6 on 2024-09-23 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('linkedin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('youtube', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('twitter', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('instagram', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsor', to='sponsors.sponsor')),
            ],
            options={
                'ordering': ['sponsor'],
            },
        ),
    ]
