# Generated by Django 5.0.6 on 2024-10-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsorship_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'ordering': ['sponsor'], 'verbose_name': 'Sponsorship', 'verbose_name_plural': 'Sponsorships'},
        ),
    ]
