# Generated by Django 5.0.6 on 2024-09-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
