# Generated by Django 5.0.6 on 2024-10-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['start_time', 'label'], 'verbose_name': 'Custom Field', 'verbose_name_plural': 'Custom Fields'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime', '-updated_at', 'title'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['username', 'first_name', 'last_name', 'type'], 'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.PositiveIntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='greenplan.organizer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['street_number', 'street_name', 'city', 'zip_code'],
            },
        ),
    ]
