# Generated by Django 5.0.6 on 2024-09-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['start_time', 'label']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime', '-updated_at', 'title']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-updated_at', 'title'], 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-14 15:15:40'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='greenplan.event'),
        ),
    ]
