# Generated by Django 5.0.6 on 2024-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0002_alter_customfield_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
