# Generated by Django 5.0.6 on 2024-10-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0003_event_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='address',
        ),
    ]
