# Generated by Django 5.0.6 on 2024-09-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0004_event_contact_email_event_contat_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contat_phone_number',
            new_name='contact_phone_number',
        ),
    ]
