# Generated by Django 5.0.6 on 2024-10-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenplan', '0004_remove_organizer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['is_private', 'start_datetime', '-updated_at', 'title'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='template',
            name='event_name',
        ),
        migrations.AddField(
            model_name='template',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='greenplan.event'),
        ),
    ]
